<a href="https://colab.research.google.com/github/estefanabermeo/Evaluacion/blob/main/Evaluacion_Pt2_EUA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **EVALUACIÓN PARTE 2 CALIFORNIA EUA**
#### Estefana Bermeo Severiano
#### A01367558

In [1]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#Carga desde un archivo .csv
eua= pd.read_csv("eua_limpio.csv", encoding = 'unicode_escape')
eua.head(5)

,Unnamed: 0,host_acceptance_rate,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,0,1.00,1,37.77028,-122.43317,3,0,1,2,202,...,1 bath,1,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/23,23/07/09,19/02/23,City Registration Pending,f
1,1,0.71,2,37.74474,-122.42089,4,0,2,2,235,...,1 bath,2,"[""Essentials"", ""Carbon monoxide alarm"", ""Hange...",--,t,06/03/23,03/05/09,06/08/17,0,f
2,2,0.73,13,37.76555,-122.45213,1,0,1,1,56,...,4 shared baths,1,"[""Security cameras on property"", ""Host greets ...",--,t,06/03/23,08/09/14,27/10/22,0,f
3,3,0.00,2,37.77564,-122.43642,4,0,2,2,575,...,1.5 baths,2,"[""Oven"", ""Cooking basics"", ""TV"", ""Smoke alarm""...",--,t,06/03/23,25/09/09,28/06/19,STR-0000264,f
4,4,0.90,2,37.76030,-122.42197,3,0,1,1,110,...,1 private bath,1,"[""Paid parking garage off premises"", ""Luggage ...",--,t,06/03/23,01/08/09,25/02/23,STR-0000028,f

**Obtener los registros que cumplan las siguientes condiciones para cada dataframe:**

In [3]:
# a) host_acceptance_rate> 50%
filtro1_eua = eua.loc[eua['host_acceptance_rate'] > 0.50]
filtro1_eua

,Unnamed: 0,host_acceptance_rate,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,0,1.00,1,37.770280,-122.433170,3,0,1,2,202,...,1 bath,1,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/23,23/07/09,19/02/23,City Registration Pending,f
1,1,0.71,2,37.744740,-122.420890,4,0,2,2,235,...,1 bath,2,"[""Essentials"", ""Carbon monoxide alarm"", ""Hange...",--,t,06/03/23,03/05/09,06/08/17,0,f
2,2,0.73,13,37.765550,-122.452130,1,0,1,1,56,...,4 shared baths,1,"[""Security cameras on property"", ""Host greets ...",--,t,06/03/23,08/09/14,27/10/22,0,f
4,4,0.90,2,37.760300,-122.421970,3,0,1,1,110,...,1 private bath,1,"[""Paid parking garage off premises"", ""Luggage ...",--,t,06/03/23,01/08/09,25/02/23,STR-0000028,f
5,5,0.95,1,37.784400,-122.479320,4,0,2,2,259,...,1 bath,2,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/23,21/10/11,17/02/23,STR-0002192,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6926,6926,0.96,7,37.716070,-122.391170,2,0,1,1,83,...,1.5 shared baths,1,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/23,03/02/23,25/02/23,2022-012006STR,f
6927,6927,0.98,32,37.788619,-122.422556,2,0,1,1,80,...,1 private bath,1,"[""Security cameras on property"", ""Self check-i...",--,t,06/03/23,13/02/23,13/02/23,Exempt,f
6929,6929,0.97,67,37.725231,-122.404776,2,0,1,1,40,...,1 shared bath,1,"[""Oven"", ""Security cameras on property"", ""Self...",--,t,06/03/23,--,--,0,f
6930,6930,1.00,6,37.753771,-122.399004,1,0,1,1,56,...,1 shared bath,1,"[""Carbon monoxide alarm"", ""Security cameras on...",--,t,06/03/23,--,--,0,t
6931,6931,1.00,9,37.791994,-122.410000,2,0,1,1,164,...,1 bath,1,"[""Security cameras on property"", ""Self check-i...",--,t,06/03/23,--,--,147904,t

In [4]:
# b) Sólo los registros con categoría “superhost”
filtro2_eua = eua.loc[eua['host_is_superhost'] == "t"]
filtro2_eua

,Unnamed: 0,host_acceptance_rate,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,0,1.00,1,37.770280,-122.433170,3,0,1,2,202,...,1 bath,1,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/23,23/07/09,19/02/23,City Registration Pending,f
4,4,0.90,2,37.760300,-122.421970,3,0,1,1,110,...,1 private bath,1,"[""Paid parking garage off premises"", ""Luggage ...",--,t,06/03/23,01/08/09,25/02/23,STR-0000028,f
7,7,1.00,2,37.717500,-122.396980,2,0,1,1,95,...,1.5 shared baths,1,"[""Self check-in"", ""Shared BBQ grill: charcoal""...",--,t,06/03/23,21/02/10,28/01/23,2022-011003STR,f
8,8,0.61,2,37.771960,-122.434770,5,0,3,3,425,...,2 baths,3,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/23,14/08/12,19/02/23,STR-0000192,f
9,9,0.84,2,37.785460,-122.461480,6,0,3,3,545,...,2 baths,3,"[""Self check-in"", ""Cooking basics"", ""Shampoo"",...",--,t,06/03/23,05/07/11,02/01/22,2022-011317STR,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6913,6913,1.00,2,37.719700,-122.463300,2,0,1,1,71,...,1 private bath,1,"[""Security cameras on property"", ""Self check-i...",--,t,06/03/23,09/02/23,13/02/23,1133735,f
6918,6918,1.00,23,37.767920,-122.424256,1,0,1,1,52,...,1 shared bath,1,"[""Security cameras on property"", ""Self check-i...",--,t,06/03/23,--,--,0,f
6919,6919,0.94,10,37.803929,-122.443176,4,0,2,2,290,...,2 baths,2,"[""Oven"", ""Security cameras on property"", ""Cook...",--,t,06/03/23,--,--,0,t
6923,6923,1.00,3,37.784690,-122.392874,2,0,1,1,110,...,1 bath,1,"[""Cooking basics"", ""Blender"", ""Shampoo"", ""TV"",...",--,t,06/03/23,--,--,0,f
6929,6929,0.97,67,37.725231,-122.404776,2,0,1,1,40,...,1 shared bath,1,"[""Oven"", ""Security cameras on property"", ""Self...",--,t,06/03/23,--,--,0,f

In [5]:
# c) Los registros que no hallan verificado identidad “ not identity_verified”
filtro3_eua = eua.loc[eua['host_identity_verified'] == "f"]
filtro3_eua

,Unnamed: 0,host_acceptance_rate,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
6,6,0.67,1,37.747660,-122.420410,2,0,1,1,100,...,1 bath,1,"[""Oven"", ""Cooking basics"", ""Blender"", ""Shampoo...",--,t,06/03/23,22/04/14,26/11/22,0,f
28,28,0.60,1,37.749160,-122.429710,3,0,0,2,95,...,1 bath,0,"[""Oven"", ""Cooking basics"", ""Shampoo"", ""Host gr...",--,t,06/03/23,05/06/10,19/06/22,0,f
38,38,0.00,1,37.751170,-122.425670,1,0,1,1,120,...,Half-bath,1,"[""Carbon monoxide alarm"", ""First aid kit"", ""Sm...",--,t,06/03/23,06/12/11,22/09/14,0,f
39,39,1.00,1,37.803560,-122.404370,2,0,1,1,175,...,1 bath,1,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/23,17/05/18,26/06/21,0,f
71,71,0.95,5,37.792780,-122.410070,10,0,1,4,1000,...,1 bath,1,"[""Essentials"", ""Bed linens"", ""Carbon monoxide ...",--,t,06/03/23,20/01/12,23/10/22,City Registration Pending,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6885,6885,0.98,24,37.800850,-122.433658,1,0,1,1,75,...,1 shared bath,1,"[""Carbon monoxide alarm"", ""Lock on bedroom doo...",--,t,06/03/23,--,--,0,f
6905,6905,1.00,2,37.731587,-122.496157,2,0,1,1,76,...,1 bath,1,"[""Contact host body soap"", ""Security cameras o...",--,t,06/03/23,05/02/23,28/02/23,2022-013018STR,t
6931,6931,1.00,9,37.791994,-122.410000,2,0,1,1,164,...,1 bath,1,"[""Security cameras on property"", ""Self check-i...",--,t,06/03/23,--,--,147904,t
6932,6932,0.00,1,37.763060,-122.432023,2,0,1,1,228,...,1 bath,1,"[""Cooking basics"", ""Luggage dropoff allowed"", ...",--,t,06/03/23,03/03/23,03/03/23,2023-001477STR,f
6933,6933,0.00,1,37.777633,-122.416478,1,0,1,1,104,...,1 shared bath,1,"[""TV"", ""Free dryer â In unit"", ""Mountain vie...",--,t,06/03/23,--,--,0,f

In [6]:
# d) Los registro cuyo property_type = “Private room” y “Hotel room”
filtro4_eua = eua[~(eua["property_type"] == "Private room") & ~(eua["property_type"] == "Hotel room")]
filtro4_eua

,Unnamed: 0,host_acceptance_rate,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,0,1.00,1,37.770280,-122.433170,3,0,1,2,202,...,1 bath,1,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/23,23/07/09,19/02/23,City Registration Pending,f
1,1,0.71,2,37.744740,-122.420890,4,0,2,2,235,...,1 bath,2,"[""Essentials"", ""Carbon monoxide alarm"", ""Hange...",--,t,06/03/23,03/05/09,06/08/17,0,f
2,2,0.73,13,37.765550,-122.452130,1,0,1,1,56,...,4 shared baths,1,"[""Security cameras on property"", ""Host greets ...",--,t,06/03/23,08/09/14,27/10/22,0,f
3,3,0.00,2,37.775640,-122.436420,4,0,2,2,575,...,1.5 baths,2,"[""Oven"", ""Cooking basics"", ""TV"", ""Smoke alarm""...",--,t,06/03/23,25/09/09,28/06/19,STR-0000264,f
4,4,0.90,2,37.760300,-122.421970,3,0,1,1,110,...,1 private bath,1,"[""Paid parking garage off premises"", ""Luggage ...",--,t,06/03/23,01/08/09,25/02/23,STR-0000028,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6931,6931,1.00,9,37.791994,-122.410000,2,0,1,1,164,...,1 bath,1,"[""Security cameras on property"", ""Self check-i...",--,t,06/03/23,--,--,147904,t
6932,6932,0.00,1,37.763060,-122.432023,2,0,1,1,228,...,1 bath,1,"[""Cooking basics"", ""Luggage dropoff allowed"", ...",--,t,06/03/23,03/03/23,03/03/23,2023-001477STR,f
6933,6933,0.00,1,37.777633,-122.416478,1,0,1,1,104,...,1 shared bath,1,"[""TV"", ""Free dryer â In unit"", ""Mountain vie...",--,t,06/03/23,--,--,0,f
6934,6934,0.50,3,37.738325,-122.396603,2,0,1,1,65,...,1 shared bath,1,"[""Essentials"", ""Carbon monoxide alarm"", ""Centr...",--,t,06/03/23,--,--,2022-012562STR,f
6935,6935,0.00,2,37.786442,-122.457006,2,0,1,1,375,...,1 bath,1,"[""Carbon monoxide alarm"", ""Security cameras on...",--,t,06/03/23,--,--,0,t

In [7]:
# e) Los registros que cuenten con bathroom > 1
filtro5_eua = eua.loc[eua['bathrooms'] > 1]
filtro5_eua

Empty DataFrame
Columns: [Unnamed: 0, host_acceptance_rate, host_listings_count, latitude, longitude, accommodates, bathrooms, bedrooms, beds, price, minimum_nights, maximum_nights, minimum_minimum_nights, maximum_minimum_nights, minimum_maximum_nights, maximum_maximum_nights, minimum_nights_avg_ntm, maximum_nights_avg_ntm, calendar_updated, availability_30, availability_60, availability_90, availability_365, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, review_scores_rating, review_scores_accuracy, review_scores_cleanliness, review_scores_checkin, review_scores_communication, review_scores_location, review_scores_value, calculated_host_listings_count, calculated_host_listings_count_entire_homes, calculated_host_listings_count_private_rooms, calculated_host_listings_count_shared_rooms, reviews_per_month, Ã¯Â»Â¿id, listing_url, scrape_id, last_scraped, source, name, description, neighborhood_overview, picture_url, host_id, host_url, host_name, host_since, host_location, host_about, host_response_time, host_is_superhost, host_thumbnail_url, host_picture_url, host_neighbourhood, host_verifications, host_has_profile_pic, host_identity_verified, neighbourhood, neighbourhood_cleansed, neighbourhood_group_cleansed, property_type, room_type, bathrooms.1, bathrooms_text, bedrooms.1, amenities, calendar_updated.1, has_availability, calendar_last_scraped, first_review, last_review, license, instant_bookable]
Index: []

[0 rows x 77 columns]

In [8]:
# f) Los registros cuyo precio sea mayor de $10,000 y que sean de tipo “Entire home”
filtro6_eua = eua[~(eua["price"] > 10000) & ~(eua["property_type"] == "Entire home")]
filtro6_eua

,Unnamed: 0,host_acceptance_rate,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,0,1.00,1,37.770280,-122.433170,3,0,1,2,202,...,1 bath,1,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/23,23/07/09,19/02/23,City Registration Pending,f
1,1,0.71,2,37.744740,-122.420890,4,0,2,2,235,...,1 bath,2,"[""Essentials"", ""Carbon monoxide alarm"", ""Hange...",--,t,06/03/23,03/05/09,06/08/17,0,f
2,2,0.73,13,37.765550,-122.452130,1,0,1,1,56,...,4 shared baths,1,"[""Security cameras on property"", ""Host greets ...",--,t,06/03/23,08/09/14,27/10/22,0,f
3,3,0.00,2,37.775640,-122.436420,4,0,2,2,575,...,1.5 baths,2,"[""Oven"", ""Cooking basics"", ""TV"", ""Smoke alarm""...",--,t,06/03/23,25/09/09,28/06/19,STR-0000264,f
4,4,0.90,2,37.760300,-122.421970,3,0,1,1,110,...,1 private bath,1,"[""Paid parking garage off premises"", ""Luggage ...",--,t,06/03/23,01/08/09,25/02/23,STR-0000028,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6931,6931,1.00,9,37.791994,-122.410000,2,0,1,1,164,...,1 bath,1,"[""Security cameras on property"", ""Self check-i...",--,t,06/03/23,--,--,147904,t
6932,6932,0.00,1,37.763060,-122.432023,2,0,1,1,228,...,1 bath,1,"[""Cooking basics"", ""Luggage dropoff allowed"", ...",--,t,06/03/23,03/03/23,03/03/23,2023-001477STR,f
6933,6933,0.00,1,37.777633,-122.416478,1,0,1,1,104,...,1 shared bath,1,"[""TV"", ""Free dryer â In unit"", ""Mountain vie...",--,t,06/03/23,--,--,0,f
6934,6934,0.50,3,37.738325,-122.396603,2,0,1,1,65,...,1 shared bath,1,"[""Essentials"", ""Carbon monoxide alarm"", ""Centr...",--,t,06/03/23,--,--,2022-012562STR,f
6935,6935,0.00,2,37.786442,-122.457006,2,0,1,1,375,...,1 bath,1,"[""Carbon monoxide alarm"", ""Security cameras on...",--,t,06/03/23,--,--,0,t

In [9]:
# g) Los registros cuyo review_scores_cleanliness > 4.5
filtro7_eua = eua.loc[eua['review_scores_cleanliness'] > 4.5]
filtro7_eua

,Unnamed: 0,host_acceptance_rate,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,0,1.00,1,37.770280,-122.433170,3,0,1,2,202,...,1 bath,1,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/23,23/07/09,19/02/23,City Registration Pending,f
1,1,0.71,2,37.744740,-122.420890,4,0,2,2,235,...,1 bath,2,"[""Essentials"", ""Carbon monoxide alarm"", ""Hange...",--,t,06/03/23,03/05/09,06/08/17,0,f
3,3,0.00,2,37.775640,-122.436420,4,0,2,2,575,...,1.5 baths,2,"[""Oven"", ""Cooking basics"", ""TV"", ""Smoke alarm""...",--,t,06/03/23,25/09/09,28/06/19,STR-0000264,f
4,4,0.90,2,37.760300,-122.421970,3,0,1,1,110,...,1 private bath,1,"[""Paid parking garage off premises"", ""Luggage ...",--,t,06/03/23,01/08/09,25/02/23,STR-0000028,f
5,5,0.95,1,37.784400,-122.479320,4,0,2,2,259,...,1 bath,2,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/23,21/10/11,17/02/23,STR-0002192,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6924,6924,0.96,7,37.716079,-122.390953,2,0,1,1,79,...,1.5 shared baths,1,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/23,07/02/23,07/02/23,2022-012006STR,f
6925,6925,0.96,7,37.716214,-122.391460,2,0,1,1,85,...,1.5 shared baths,1,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/23,10/02/23,24/02/23,2022-012006STR,f
6926,6926,0.96,7,37.716070,-122.391170,2,0,1,1,83,...,1.5 shared baths,1,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/23,03/02/23,25/02/23,2022-012006STR,f
6927,6927,0.98,32,37.788619,-122.422556,2,0,1,1,80,...,1 private bath,1,"[""Security cameras on property"", ""Self check-i...",--,t,06/03/23,13/02/23,13/02/23,Exempt,f
6932,6932,0.00,1,37.763060,-122.432023,2,0,1,1,228,...,1 bath,1,"[""Cooking basics"", ""Luggage dropoff allowed"", ...",--,t,06/03/23,03/03/23,03/03/23,2023-001477STR,f

In [10]:
# h) Los registros cuyo review_scores_value > 4.9
filtro8_eua = eua.loc[eua['review_scores_value'] > 4.9]
filtro8_eua

,Unnamed: 0,host_acceptance_rate,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
9,9,0.84,2,37.785460,-122.461480,6,0,3,3,545,...,2 baths,3,"[""Self check-in"", ""Cooking basics"", ""Shampoo"",...",--,t,06/03/23,05/07/11,02/01/22,2022-011317STR,f
24,24,1.00,2,37.762160,-122.450220,2,0,1,1,180,...,1 bath,1,"[""Oven"", ""Security cameras on property"", ""Cook...",--,t,06/03/23,01/08/14,14/02/23,0,f
26,26,1.00,1,37.762370,-122.429920,2,0,1,1,99,...,1.5 shared baths,1,"[""Essentials"", ""Bed linens"", ""Dishes and silve...",--,t,06/03/23,14/01/10,20/02/23,STR-0000057,f
46,46,1.00,2,37.717270,-122.436440,1,0,1,1,85,...,1.5 shared baths,1,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""S...",--,t,06/03/23,20/05/18,31/01/23,STR-0003035,t
53,53,1.00,1,37.744030,-122.417550,2,0,2,2,80,...,1 shared bath,2,"[""Oven"", ""Cooking basics"", ""Blender"", ""Shampoo...",--,t,06/03/23,23/07/12,01/03/23,STR-0001006,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6920,6920,0.99,9,37.801789,-122.426501,2,0,1,1,107,...,1 private bath,1,"[""Security cameras on property"", ""Self check-i...",--,t,06/03/23,10/02/23,10/02/23,Exempt,t
6924,6924,0.96,7,37.716079,-122.390953,2,0,1,1,79,...,1.5 shared baths,1,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/23,07/02/23,07/02/23,2022-012006STR,f
6925,6925,0.96,7,37.716214,-122.391460,2,0,1,1,85,...,1.5 shared baths,1,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/23,10/02/23,24/02/23,2022-012006STR,f
6927,6927,0.98,32,37.788619,-122.422556,2,0,1,1,80,...,1 private bath,1,"[""Security cameras on property"", ""Self check-i...",--,t,06/03/23,13/02/23,13/02/23,Exempt,f
6932,6932,0.00,1,37.763060,-122.432023,2,0,1,1,228,...,1 bath,1,"[""Cooking basics"", ""Luggage dropoff allowed"", ...",--,t,06/03/23,03/03/23,03/03/23,2023-001477STR,f

In [11]:
# i) Los registros cuya availability_365< 100
filtro9_eua = eua.loc[eua['availability_365'] < 100]
filtro9_eua

,Unnamed: 0,host_acceptance_rate,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
5,5,0.95,1,37.784400,-122.479320,4,0,2,2,259,...,1 bath,2,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/23,21/10/11,17/02/23,STR-0002192,f
8,8,0.61,2,37.771960,-122.434770,5,0,3,3,425,...,2 baths,3,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/23,14/08/12,19/02/23,STR-0000192,f
9,9,0.84,2,37.785460,-122.461480,6,0,3,3,545,...,2 baths,3,"[""Self check-in"", ""Cooking basics"", ""Shampoo"",...",--,t,06/03/23,05/07/11,02/01/22,2022-011317STR,f
11,11,1.00,9,37.792330,-122.424310,1,0,1,1,55,...,--,1,"[""Essentials"", ""Bed linens"", ""Carbon monoxide ...",--,t,06/03/23,10/07/11,28/02/23,0,f
15,15,0.80,5,37.772520,-122.438460,2,0,1,1,220,...,1 bath,1,"[""TV with standard cable, DVD player, HBO Max""...",--,t,06/03/23,27/06/12,26/09/22,0,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6913,6913,1.00,2,37.719700,-122.463300,2,0,1,1,71,...,1 private bath,1,"[""Security cameras on property"", ""Self check-i...",--,t,06/03/23,09/02/23,13/02/23,1133735,f
6917,6917,1.00,1,37.748247,-122.433441,2,0,1,1,222,...,1 bath,1,"[""Oven"", ""Security cameras on property"", ""Self...",--,t,06/03/23,--,--,2023-001339STR,f
6918,6918,1.00,23,37.767920,-122.424256,1,0,1,1,52,...,1 shared bath,1,"[""Security cameras on property"", ""Self check-i...",--,t,06/03/23,--,--,0,f
6923,6923,1.00,3,37.784690,-122.392874,2,0,1,1,110,...,1 bath,1,"[""Cooking basics"", ""Blender"", ""Shampoo"", ""TV"",...",--,t,06/03/23,--,--,0,f
6931,6931,1.00,9,37.791994,-122.410000,2,0,1,1,164,...,1 bath,1,"[""Security cameras on property"", ""Self check-i...",--,t,06/03/23,--,--,147904,t

In [12]:
# j) Los registros cuya host_response_time sea “within an hour”
filtro10_eua = eua.loc[eua['host_response_time'] == "within an hour"]
filtro10_eua

,Unnamed: 0,host_acceptance_rate,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,...,bathrooms_text,bedrooms.1,amenities,calendar_updated.1,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,0,1.00,1,37.770280,-122.433170,3,0,1,2,202,...,1 bath,1,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/23,23/07/09,19/02/23,City Registration Pending,f
2,2,0.73,13,37.765550,-122.452130,1,0,1,1,56,...,4 shared baths,1,"[""Security cameras on property"", ""Host greets ...",--,t,06/03/23,08/09/14,27/10/22,0,f
4,4,0.90,2,37.760300,-122.421970,3,0,1,1,110,...,1 private bath,1,"[""Paid parking garage off premises"", ""Luggage ...",--,t,06/03/23,01/08/09,25/02/23,STR-0000028,f
5,5,0.95,1,37.784400,-122.479320,4,0,2,2,259,...,1 bath,2,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",--,t,06/03/23,21/10/11,17/02/23,STR-0002192,f
12,12,0.82,2,37.728330,-122.441250,2,0,1,1,235,...,1 bath,1,"[""Oven"", ""Cooking basics"", ""Shampoo"", ""Host gr...",--,t,06/03/23,17/06/12,25/10/22,STR-0004820,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6929,6929,0.97,67,37.725231,-122.404776,2,0,1,1,40,...,1 shared bath,1,"[""Oven"", ""Security cameras on property"", ""Self...",--,t,06/03/23,--,--,0,f
6930,6930,1.00,6,37.753771,-122.399004,1,0,1,1,56,...,1 shared bath,1,"[""Carbon monoxide alarm"", ""Security cameras on...",--,t,06/03/23,--,--,0,t
6931,6931,1.00,9,37.791994,-122.410000,2,0,1,1,164,...,1 bath,1,"[""Security cameras on property"", ""Self check-i...",--,t,06/03/23,--,--,147904,t
6934,6934,0.50,3,37.738325,-122.396603,2,0,1,1,65,...,1 shared bath,1,"[""Essentials"", ""Carbon monoxide alarm"", ""Centr...",--,t,06/03/23,--,--,2022-012562STR,f
6935,6935,0.00,2,37.786442,-122.457006,2,0,1,1,375,...,1 bath,1,"[""Carbon monoxide alarm"", ""Security cameras on...",--,t,06/03/23,--,--,0,t

In [13]:
# Convertir a csv cada filtro
filtro1_eua.to_csv("filtro1_eua.csv")
filtro2_eua.to_csv("filtro2_eua.csv")
filtro3_eua.to_csv("filtro3_eua.csv")
filtro4_eua.to_csv("filtro4_eua.csv")
filtro5_eua.to_csv("filtro5_eua.csv")
filtro6_eua.to_csv("filtro6_eua.csv")
filtro7_eua.to_csv("filtro7_eua.csv")
filtro8_eua.to_csv("filtro8_eua.csv")
filtro9_eua.to_csv("filtro9_eua.csv")
filtro10_eua.to_csv("filtro10_eua.csv")

In [15]:
# Descargamos cada csv
from google.colab import files   
files.download("filtro1_eua.csv")
files.download("filtro2_eua.csv")
files.download("filtro3_eua.csv")
files.download("filtro4_eua.csv")
files.download("filtro5_eua.csv")
files.download("filtro6_eua.csv")
files.download("filtro7_eua.csv")
files.download("filtro8_eua.csv")
files.download("filtro9_eua.csv")
files.download("filtro10_eua.csv")